name: squad
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - ujson
  - numpy
  - pip
  - spacy
  - tensorboard
  - tensorflow
  - tensorboardX
  - tqdm
  - urllib3
  - pytorch
  - cudatoolkit=11.3
